Parser/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home_project'),
    url(r'^parser/', include('ParserApp.urls', namespace='parserapp')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ParserApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'parserapp'

urlpatterns = [
    url(r'^$', views.home_page, name='home_app'),
    url(r'^guias/$', views.GuiasList.as_view(), name='guias'),
    url(r'^guias/(?P<pk>\d+)/$', views.GuiasDetail.as_view(), name='guia_detail'),
    url(r'^guias/EditarGuia/(?P<pk>\d+)/$', views.GuiaUpdateView.as_view(), name='guia_update'),
    url(r'^guias/NuevaGuia/$', views.CreateGuiaView.as_view(), name='nueva_guia'),
    url(r'^guias/GuardarXml/(?P<pk>\d+)/$', views.guardar_xml, name='guardar_xml'),
    url(r'^guias/GuardarCsv/(?P<pk>\d+)/$', views.guardar_csv, name='guardar_csv'),
    url(r'^diccionariosdimesiones/lista/$', views.DiccionariosDimensionesList.as_view(), name='diccionarios_dimensiones'),
    url(r'^diccionariosdimensiones/(?P<pk>\d+)/$', views.DiccionarioDimensionesDetail.as_view(), name='diccionarios_dimensiones_detail'),
    url(r'^diccionariosvariable/lista/$', views.DiccionariosVariableList.as_view(), name='diccionarios_variable'),
    url(r'^diccionariosvariable/(?P<pk>\d+)/$', views.DiccionarioVariableDetail.as_view(), name='diccionarios_variable_detail'),
    url(r'^ExpresionRegular/$', views.ExpresionRegular.as_view(), name='expresionregular'),
    url(r'test/all/$', views.test, name='test_all'),
]

ParserApp/models.py
import datetime
from django import forms
from django.db import models
from django.urls import reverse
from django.contrib import admin

from ParserApp.Back import JsonToXml as ToXml, ToJson, JsonToCsv as ToCsv


# Poryecto, Cadena, plataforma --------------------------------------
class Proyecto(models.Model):
    nombre = models.CharField(max_length=128)
    fields = ('nombre',)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


# 'unificacion' es el valor para usar en los diccionarios como base
class Cadena(models.Model):
    nombre = models.CharField(max_length=128)
    proyecto = models.ForeignKey('Proyecto',
                                 on_delete=models.PROTECT,
                                 related_name='proyecto')

    class Meta:
        ordering = ['proyecto', 'nombre']

    def __str__(self):
        return str(self.proyecto) + " " + self.nombre


# app | web
class Plataforma(models.Model):
    nombre = models.CharField(max_length=64, primary_key=True)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


# Expresiones Regulares -------------------------
class ExpresionRegular(models.Model):
    proyecto = models.ForeignKey('Proyecto', on_delete=models.PROTECT, related_name='expresionregular')
    nombre = models.CharField(max_length=256, primary_key=True)
    regexp = models.CharField(max_length=1024, default='.+')

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        if len(str(self.regexp)) > 50:
            mostrar_regexp = self.regexp[0:50] + '…'
        else:
            mostrar_regexp = self.regexp
        return self.nombre


# Diccionario de variables de las guías -------------------------
class DiccionarioVariable(models.Model):
    cadena = models.ForeignKey('Cadena',
                               on_delete=models.PROTECT,
                               related_name='diccionario_variable')
    plataforma = models.ForeignKey('Plataforma',
                                   on_delete=models.PROTECT,
                                   related_name='diccionario_variable')

    class Meta:
        ordering = ['cadena', 'plataforma']
        unique_together = (('cadena', 'plataforma'),)

    def __str__(self):
        return str(self.cadena) + " - " + str(self.plataforma)


class Variable(models.Model):
    variable = models.CharField(max_length=128)
    diccionario = models.ForeignKey('DiccionarioVariable',
                                    on_delete=models.CASCADE,
                                    related_name='variable')
    regexp = models.ForeignKey('ExpresionRegular',
                                         on_delete=models.CASCADE,
                                         related_name='variable_guia')

    def __str__(self):
        return str(self.diccionario) + ' | ' + str(self.variable)

    class Meta:
        ordering = ['diccionario', 'variable',]
        unique_together = (('variable', 'diccionario'),)


# Diccionario dimensiones ---------------------------------
class DiccionarioDimensiones(models.Model):
    cadena = models.ForeignKey('Cadena', on_delete=models.PROTECT,
                               related_name='diccionario_dimension')
    plataforma = models.ForeignKey('Plataforma', on_delete=models.PROTECT,
                                   related_name='diccionario_dimension')

    class Meta:
        ordering = ['cadena', 'plataforma']
        unique_together = (('cadena', 'plataforma'),)

    def __str__(self):
        return str(self.cadena) + " - " + str(self.plataforma)


class Dimension(models.Model):
    parametro = models.CharField(max_length=32)
    diccionario = models.ForeignKey('DiccionarioDimensiones', on_delete=models.CASCADE,
                                    related_name='dimension')
    regexp = models.ForeignKey('ExpresionRegular',
                                         on_delete=models.CASCADE,
                                         related_name='dimension')
    nombre = models.CharField(max_length=256, blank=True)
    datalayer = models.CharField(max_length=512, blank=True)
    ejemplo = models.CharField(max_length=512, blank=True)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return str(self.diccionario) + ' | ' + self.parametro + " (" + self.nombre + ")"

    class Meta:
        ordering = ['diccionario', 'parametro',]
        unique_together = (('parametro', 'diccionario'),)


# Guía ------------------------------------------------------
class Guia(models.Model):
    # proyecto = models.ForeignKey('Proyecto', on_delete=models.PROTECT, related_name='guia')
    cadena = models.ForeignKey('Cadena', on_delete=models.PROTECT, related_name='guias')
    plataforma = models.ForeignKey('Plataforma', on_delete=models.PROTECT, related_name='guias')
    version = models.CharField(max_length=32)
    txt = models.TextField(blank=True)

    def __str__(self):
        return str(self.cadena) + " - " + str(self.plataforma) + " - " + str(self.version)

    def get_absolute_url(self):
        return reverse("parserapp:guia_detail", args=[self.pk])

    def save(self, *args, **kwargs):
        for error in ErrorGuia.objects.filter(guia=self.id):
            error.delete()
        if Guia.objects.filter(id=self.id).count() > 0:
            self.delete()

        super(Guia, self).save(*args, **kwargs)

        # print('******************* ToJson *******************')
        ToJson.parsear_guia(doc_txt=self.txt, guia=self)
        print('******************* ToXml *******************')
        archivar_xml = ToXml.ConvertirAXml(guia=self)
        archivar_xml.convertir_a_xml(True)
        print('******************* ToCsv *******************')
        archivar_csv = ToCsv.ArchivarCsv(guia=self)
        archivar_csv.convertir_a_csv(True)

    class Meta:
        ordering = ['cadena', 'plataforma']


class ErrorGuia(models.Model):
    guia = models.ForeignKey('Guia', on_delete=models.CASCADE, related_name='error')
    seccion = models.CharField(max_length=64)
    error = models.TextField(blank=True)

    def __str__(self):
        return str(self.guia) + ' | ' + str(self.seccion)


# Json ------------------------------------------------------
class Json(models.Model):
    guia = models.OneToOneField(Guia, on_delete=models.CASCADE, primary_key=True)
    fecha_creacion = models.DateField(default=datetime.date.today)
    txt = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.guia)

    def get_absolute_url(self):
        return reverse("parserapp:guias")


class Seccion(models.Model):
    json = models.ForeignKey('Json', on_delete=models.CASCADE, related_name='secciones')
    nombre = models.CharField(max_length=128, blank=True)
    indice = models.CharField(max_length=32)

    def __str__(self):
        return str(self.indice) + "- " + str(self.nombre)


class Subseccion(models.Model):
    seccion = models.ForeignKey('Seccion', on_delete=models.CASCADE, related_name='subsecciones', blank=True, null=True)
    subseccion_padre = models.ForeignKey("self", models.CASCADE, blank=True, null=True)
    nombre = models.CharField(max_length=128, blank=True)
    indice = models.CharField(max_length=32)

    def __str__(self):
        return str(self.indice) + "- " + str(self.nombre)


class Vista(models.Model):
    subseccion = models.ForeignKey('Subseccion', models.CASCADE, related_name='vistas')
    vista = models.CharField(max_length=128)
    pagename = models.CharField(max_length=256, blank=True)
    pagetitle = models.CharField(max_length=256, blank=True)
    pagetype = models.CharField(max_length=128, blank=True)
    seccion = models.CharField(max_length=128, blank=True)
    comentarios = models.TextField(blank=True)

    def __str__(self):
        return self.vista


class DimensionesPageview(models.Model):
    vista = models.ForeignKey('Vista', models.CASCADE, related_name='dimensionespageview')
    dimension = models.CharField(max_length=32)

    def dimension_datos(self):
        dimension_obj = dict()
        try:
            dimension_obj = Dimension.objects.get(parametro=self.dimension)
        except (Dimension.DoesNotExist, Dimension.MultipleObjectsReturned):
            return ['', '']

        return [dimension_obj.nombre, dimension_obj.ejemplo]


class Evento(models.Model):
    vista = models.ForeignKey('Vista', models.CASCADE, related_name='eventos')
    accion = models.CharField(max_length=128)
    clase_funcional = models.CharField(max_length=128)
    categoria = models.CharField(max_length=128)
    etiqueta = models.CharField(max_length=128, blank=True)
    lanzamiento = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.accion


class DimensionesEvento(models.Model):
    evento = models.ForeignKey('Evento', models.CASCADE, related_name='dimensionesevento')
    dimension = models.CharField(max_length=32)

    def __str__(self):
        return str(self.evento) + ' | ' + str(self.dimension)


# Test ------------------------------------------------------
class Test(models.Model):
    guia = models.ForeignKey(Guia, on_delete=models.CASCADE, related_name='test')
    json = models.TextField()
    csv = models.TextField()
    xml = models.TextField()

    def __str__(self):
        return str(self.guia)

ParserApp/forms.py
from builtins import print
from django import forms
from .models import Guia, Proyecto, Cadena, Plataforma
from django.utils.translation import gettext_lazy as _
import html



class GuiaForm(forms.ModelForm):
    proyecto_list = list()
    for proyec in Proyecto.objects.all():
        lista = list()
        lista.append(html.unescape(proyec.nombre))
        lista.append(html.unescape(proyec.nombre))
        proyecto_list.append(lista)

    cadena_list = list()
    for cad in Cadena.objects.all():
        lista = list()
        lista.append(html.unescape(str(cad)))
        lista.append(html.unescape(cad.nombre))
        cadena_list.append(lista)

    proyecto = forms.ChoiceField(label="Proxecto",
                                 choices=proyecto_list,
                                 widget=forms.Select(attrs={'class':"form-control"}))
    cadena = forms.ChoiceField(label="Cadea",
                               choices=cadena_list,
                               widget=forms.Select(attrs={'class': "form-control"}))
    plataforma = forms.ModelChoiceField(label='Plataforma',
                                        queryset=Plataforma.objects.all(),
                                        widget=forms.Select(attrs={'class': "form-control"}))
    version = forms.CharField(label='Versión',
                              widget=forms.TextInput(attrs={'class': "form-control"}))
    txt = forms.CharField(label='Texto da guía',
                          widget=forms.Textarea(attrs={'class': "form-control"}))

    def clean(self):
        cleaned_data = super(GuiaForm, self).clean()
        proyecto_nombre = cleaned_data.get('proyecto')
        cadena_nombre = cleaned_data.get('cadena')
        cleaned_data['proyecto'] = Proyecto.objects.get(nombre=proyecto_nombre)
        cleaned_data['cadena'] = Cadena.objects.get(nombre=" ".join(cadena_nombre.split(' ')[2:]), proyecto=cleaned_data['proyecto'].id)

    class Meta:
        model = Guia
        fields = ('proyecto', 'cadena', 'plataforma', 'version', 'txt')

ParserApp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.http import HttpResponse
from .forms import GuiaForm
from .Back.Test import make_all_tests
from ParserApp.Back import JsonToXml as ToXml, JsonToCsv as ToCsv
from ParserApp.models import Guia
import codecs

from . import models


# Create your views here.
def home_page(request):
    return render(request, 'parserapp/home_parser_app.html')


class GuiasList(ListView):
    model = models.Guia

    ordering = ['cadena', 'plataforma', 'version']


class GuiasDetail(DetailView):
    model = models.Guia


class GuiaUpdateView(UpdateView):
    redirect_field_name = 'parserapp/guia_detail.html'

    form_class = GuiaForm
    model = models.Guia


class CreateGuiaView(CreateView):
    redirect_field_name = 'parserapp/guia_detail.html'

    form_class = GuiaForm
    model = models.Guia


class DiccionariosDimensionesList(ListView):
    model = models.DiccionarioDimensiones


class DiccionarioDimensionesDetail(DetailView):
    model = models.DiccionarioDimensiones


class DiccionariosVariableList(ListView):
    model = models.DiccionarioVariable


class DiccionarioVariableDetail(DetailView):
    model = models.DiccionarioVariable


class ExpresionRegular(ListView):
    model = models.ExpresionRegular


def guardar_xml(request, pk):
    guia = Guia.objects.get(pk=pk)
    archivar_xml = ToXml.ConvertirAXml(guia)
    salida = archivar_xml.convertir_a_xml(False)
    filename = str(guia) + '.xml'

    response = HttpResponse(content_type='text/xml')
    response['Content-Disposition'] = 'attachment; filename="' + filename + '"'
    response.write(salida)
    return response


def guardar_csv(request, pk):
    guia = Guia.objects.get(pk=pk)
    archivar_csv = ToCsv.ArchivarCsv(guia)
    csv_txt = archivar_csv.convertir_a_csv(False)
    salida = str(csv_txt, 'utf-8-sig')
    filename = str(guia) + '.csv'

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="' + filename + '"'

    response.write(salida)
    return response

def test(request):
    make_all_tests()

    return render(request, 'base.html')

ParserApp/templates/ParserApp/diccionariodimensiones_detail.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}

<h3>{{ diccionariodimensiones }}</h3>
<ul style="list-style-type: none">
{% for dimension in diccionariodimensiones.dimension.all %}
    <hr />
    <li><strong>{{ dimension.parametro }}</strong></li>
    <ul style="list-style-type: none;">
        <li style=" margin-left: 0;" >Expresión regular:<p style="padding-left: 1em">{{ dimension.regexp.regexp }}</p></li>
        {% if dimension.nombre %}
            <li>Nome<p style="padding-left: 1em">{{ dimension.nombre }}</p></li>
        {% endif %}
        {% if dimension.datalayer %}
            <li>DataLayer:<p style="padding-left: 1em">{{ dimension.datalayer }}</p></li>
        {% endif %}
        {% if dimension.ejemplo %}
            <li>Exemplo:<br /><p style="padding-left: 1em">{{ dimension.ejemplo }}</p></li>
        {% endif %}
        {% if dimension.descripcion %}
            <li>Descrición:<br /><p style="padding-left: 1em">{{ dimension.descripcion }}</p></li>
        {% endif %}
    </ul>

{% endfor %}
</ul>
{% endblock %}

ParserApp/templates/ParserApp/diccionariodimensiones_list.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}

<h3>Lista de diccionarios de dimensións</h3>
<ul>
{% for diccionario in diccionariodimensiones_list %}
    <li><a href="{% url 'parserapp:diccionarios_dimensiones_detail' pk=diccionario.pk %}">{{ diccionario }}</a></li>
{% endfor %}
</ul>
{% endblock %}

ParserApp/templates/ParserApp/diccionariovariable_detail.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}

<h3>{{ diccionariovariable }}</h3>
<ul style="list-style-type: none">
{% for variable in diccionariovariable.variable.all %}
    <hr />
    <li><strong>{{ variable.variable }}</strong></li>
    <ul style="list-style-type: none;">
        <li style=" margin-left: 0;" >Expresión regular:<p style="padding-left: 1em">{{ variable.regexp.regexp }}</p></li>
    </ul>

{% endfor %}
</ul>
{% endblock %}

ParserApp/templates/ParserApp/diccionariovariable_list.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}

<h3>Lista de diccionarios de variables das guías</h3>
<ul>
{% for diccionario in diccionariovariable_list %}
    <li><a href="{% url 'parserapp:diccionarios_variable_detail' pk=diccionario.pk %}">{{ diccionario }}</a></li>
{% endfor %}
</ul>
{% endblock %}

ParserApp/templates/ParserApp/expresionregular_list.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}


<h3>Diccionario de Expresiones Regulares</h3>
<ul>
{% for regexp in expresionregular_list %}
    <li><strong style="color:blue">{{ regexp }}</strong><br />{{ regexp.regexp }}</li><br />
{% endfor %}
</ul>
{% endblock %}

ParserApp/templates/ParserApp/guia_detail.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}
{% load guia_extras %}
{% load staticfiles %}

<!-- Loading css async -->
<script>
var linkElement = document.createElement("link");
linkElement.rel = "stylesheet";
linkElement.href = "{% static 'parserapp/basic.css' %}";
document.head.appendChild(linkElement);
</script>


<h2>{{ guia.cadena.nombre }} {{ guia.plataforma }}</h2>
<h3>Versión: {{ guia.version }}</h3>
<p style="margin-top: 25px;">
    <a href="{% url 'parserapp:guia_update' pk=guia.pk %}" class="btn btn-warning">Editar guía</a>
</p>
<p>
    <a href="{% url 'parserapp:guardar_xml' pk=guia.pk %}" class="btn btn-success">Gardar XML</a>
</p>
<p>
    <a href="{% url 'parserapp:guardar_csv' pk=guia.pk %}" class="btn btn-success">Gardar CSV</a>
</p>
<hr />
{% if guia.error.all.count > 0 %}
<p style="color:red;">Errores:</p>
<p>
    <p>To Json</p>
    <ul style="list-style-type:none">
    {% for error in guia.error.all|errores_en_seccion:"ToJson" %}
        <li>{{ error.error }}</li>
    {% endfor %}
    </ul>
    <p>To Xml</p>
    <ul style="list-style-type:none">
    {% for error in guia.error.all|errores_en_seccion:"ToXml" %}
        <li>{{ error.error }}</li>
    {% endfor %}
    </ul>
    <p>To Csv</p>
    <ul style="list-style-type:none">
    {% for error in guia.error.all|errores_en_seccion:"ToCsv" %}
        <li>{{ error.error }}</li>
    {% endfor %}
    </ul>
</p>
{% endif %}

<!--
*******************************
    CONTENIDO DE LA GUÍA
*******************************
-->
<div class="guide_content">
    {% for seccion in guia.json.secciones.all %}
    <h3>{{ subseccion.indice }} {{ subseccion.nombre }}</h3>

        {% for subseccion in seccion.subsecciones.all %}
        <h4>{{ subseccion.indice }} {{ subseccion.nombre }}</h4>

            {% for vista in subseccion.vistas.all %}
            <p class="vista"><strong>VISTA</strong>{{ vista.pagename }}</p>

            <table class="vista-tabla">
                <tr>
                    <td colspan="3"><strong>Pagename: </strong>{{ vsita.pagename }}</td>
                </tr>
                <tr>
                    <td><strong>Sección: </strong>{{ vista.seccion }}</td>
                    <td><strong>Page type: </strong>{{ vista.pagetype }}</td>
                    <td><strong>Page title: </strong>{{ vista.pagetitle }}</td>
                </tr>
            </table>

            <img class="img-screenshot" src="{% static 'parserapp/img_test2.png' %}" alt="Captura da vista" />
            <p class="img-title">Ilustración de mostra</p>

            <p class="blue-separator">Accións de usuario</p>
            <table class="table-eventos">
                <tr>
                    <th>C.F.</th>
                    <th>Categoría</th>
                    <th>Acción</th>
                    <th>Etiqueta</th>
                    <th>Dimens.</th>
                    <th>Lanzamiento</th>
                </tr>
                {% for evento in vista.eventos.all %}
                <tr>
                    <td>{{ evento.clase_funcional }}</td>
                    <td>{{ evento.categoria }}</td>
                    <td>{{ evento.etiqueta }}</td>
                    <td>
                    {% for dim_evento in evento.dimensionesevento.all %}
                        {{ dim_evento.dimension }},
                    {% endfor %}
                    </td>
                    <td width="35%">{{ evento.lanzamiento }}</td>
                </tr>
                {% endfor %}
            </table>

            <p class="blue-separator">Dimensiones y métricas personalizadas</p>
            <table class="table-eventos">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Valor (exemplo)</th>
                </tr>
            {% for dim_pageview in vista.dimensionespageview.all %}
                <tr>
                    <td>{{ dim_pageview.dimension }}</td>
                    <td>{{ dim_pageview.dimension_datos.0 }}</td>
                    <td>{{ dim_pageview.dimension_datos.1 }}</td>
                </tr>
            {% endfor %}
            </table>

            <p class="blue-separator">Comentarios</p>
            {% autoescape on %}
            {{ vista.comentarios | linebreaksbr }}
            {% endautoescape %}
            {% endfor %}
        {% endfor %}

    {% endfor %}
</div>

{% endblock %}

ParserApp/templates/ParserApp/guia_form.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}

<form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.label }}<br />
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit" value="Guardar" class="save btn btn-default">Gardar</button>

</form>

{% autoescape off %}

<script type="text/javascript">
$(function() {
    proyecto_value = "{{ guia.cadena.proyecto }}";
    cadena_value = "{{ guia.cadena.proyecto }}" + " " + "{{ guia.cadena.nombre }}";

    $('#id_proyecto').val(proyecto_value);
    $('#id_cadena').val(cadena_value);
})
$('#id_proyecto').change(function() {
    $('#id_cadena option').hide();
    $('#id_cadena option[value^="' + $(this).val() + '"]').show();

    $('#id_cadena').val('');
});
</script>

{% endautoescape %}

{% endblock %}

ParserApp/templates/ParserApp/guia_list.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}


<h2 style="margin-bottom: 30px;">Lista de guías</h2>
{% for guia in guia_list %}
<h4><a href="{% url 'parserapp:guia_detail' pk=guia.pk %}">{{ guia }}</a></h4>
{% endfor %}
<a style="margin-top: 15px" href="{% url 'parserapp:nueva_guia' %}" class="btn btn-success">Nova guía</a>
{% endblock %}

ParserApp/templates/ParserApp/home_parser_app.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}
 <h1></h1>
{% endblock %}

ParserApp/templates/ParserApp/json_detail.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}

<h3>{{ json }}</h3>
<ul>
{% for subseccion in json.subsecciones.all %}
    <li>{{ subseccion.indice }}. {{ subseccion.nombre }}</li>
    <ul>
        {% for vista in subseccion.vistas.all %}
        <li>Vista:<br />{{ vista.vista }}</li>
        <li>Page Name:<br />{{ vista.pagename }}</li>
        <li>Page Title:<br />{{ vista.pagetitle }}</li>
        <li>Page Type:<br />{{ vista.pagetype }}</li>
        <li>Sección:<br />{{ vista.seccion }}</li>
        <ul>
            {% for dimension in vista.dimensionespageview.all%}
                <li>{{ dimension.dimension }}</li>
            {% endfor %}
        </ul>
        <li>Eventos:</li>
        <ul>
            {% for evento in vista.eventos.all %}
            <li>Acción:<br />{{ evento.accion }}</li>
            <li>C.F.:<br />{{ evento.clase_funcional }}</li>
            <li>Categoría:<br />{{ evento.categoria }}</li>
            <li>Etiqueta:<br />{{ evento.etiqueta }}</li>
            <li>Lanzamento:<br />{{ evento.lanzamiento }}</li>
            <li>Dimensóns</li>
            <ul>
            {% for dimension in evento.dimensionesevento.all%}
                <li>{{ dimension.dimension }}</li>
            {% endfor %}
        </ul>
            {% endfor %}
        </ul>
        {% endfor %}
    </ul>


{% endfor %}
</ul>
{% endblock %}

ParserApp/templates/ParserApp/parserapp_base.html
{% extends "base.html" %}
{% block content %}

{% block content_app %}
{% endblock %}

{% endblock %}

ParserApp/templates/ParserApp/plantillaxml_detail.html
{% extends "ParserApp/parserapp_base.html" %}
{% block content_app %}
<h3>{{ plantillaxml.guia }}</h3>
<p>{{ plantillaxml.datos_xml }}</p>

{% endblock %}