Parser/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home_project'),
    url(r'^parser/', include('ParserApp.urls', namespace='parserapp')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ParserApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'parserapp'

urlpatterns = [
    url(r'^$', views.home_page, name='home_app'),
    url(r'^guias/$', views.GuiasList.as_view(), name='guias'),
    url(r'^guias/(?P<pk>\d+)/$', views.GuiasDetail.as_view(), name='guia_detail'),
    url(r'^guias/EditarGuia/(?P<pk>\d+)/$', views.GuiaUpdateView.as_view(), name='guia_update'),
    url(r'^guias/NuevaGuia/$', views.CreateGuiaView.as_view(), name='nueva_guia'),
    url(r'^guias/GuardarXml/(?P<pk>\d+)/$', views.guardar_xml, name='guardar_xml'),
    url(r'^guias/GuardarCsv/(?P<pk>\d+)/$', views.guardar_csv, name='guardar_csv'),
    url(r'^diccionariosdimesiones/lista/$', views.DiccionariosDimensionesList.as_view(), name='diccionarios_dimensiones'),
    url(r'^diccionariosdimensiones/(?P<pk>\d+)/$', views.DiccionarioDimensionesDetail.as_view(), name='diccionarios_dimensiones_detail'),
    url(r'^diccionariosvariable/lista/$', views.DiccionariosVariableList.as_view(), name='diccionarios_variable'),
    url(r'^diccionariosvariable/(?P<pk>\d+)/$', views.DiccionarioVariableDetail.as_view(), name='diccionarios_variable_detail'),
    url(r'^ExpresionRegular/$', views.ExpresionRegular.as_view(), name='expresionregular'),
    url(r'test/all/$', views.test, name='test_all'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <meta charset="utf-8">
    <title>GuideParser - Proxecto DAW - Alberto G. Reino</title>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'parserapp/basic.css' %}">
</head>
<body>
<nav class="navbar navbar-default" role="navigation" id="navbar">
    <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home_project' %}">Home</a>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'parserapp:guias' %}" class="btn btn-simple">Guías</a></li>
            <li><a href="{% url 'parserapp:diccionarios_dimensiones' %}" class="btn btn-simple">Diccionarios dimensións</a></li>
            <li><a href="{% url 'parserapp:diccionarios_variable' %}" class="btn btn-simple">Diccionarios variables de guías</a></li>
            <li><a href="{% url 'parserapp:expresionregular' %}" class="btn btn-simple">Expresións Regulares</a></li>
            <!--<li><a href="{% url 'parserapp:test_all' %}" class="btn btn-simple">Test</a></li>-->
            <li><a href="{% url 'admin:index' %}" class="btn btn-simple">Admin</a></li>
        </ul>
    </div>
</nav>
<div class="container mycontent">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends "base.html"%}
{% block content %}

<h1>Index Project.</h1>

{% endblock %}